all: tarsum

CFLAGS = -g -O2
CPPFLAGS =
LDFLAGS =
LDLIBS =

LIBARCHIVE_PREFIX =
LIBARCHIVE_INCLUDEDIR = $(LIBARCHIVE_PREFIX:%=%/include)
LIBARCHIVE_LIBDIR = $(LIBARCHIVE_PREFIX:%=%/lib)
LIBARCHIVE_CFLAGS =
LIBARCHIVE_CPPFLAGS = $(LIBARCHIVE_INCLUDEDIR:%=-I%)
LIBARCHIVE_LDFLAGS = $(LIBARCHIVE_LIBDIR:%=-L%)
LIBARCHIVE_LDLIBS = -larchive

OPENSSL_PREFIX =
OPENSSL_INCLUDEDIR = $(OPENSSL_PREFIX:%=%/include)
OPENSSL_LIBDIR = $(OPENSSL_PREFIX:%=%/lib)
OPENSSL_CFLAGS =
OPENSSL_CPPFLAGS = $(OPENSSL_INCLUDEDIR:%=-I%)
OPENSSL_LDFLAGS = $(OPENSSL_LIBDIR:%=-L%)
OPENSSL_LDLIBS = -lcrypto

WARN_CFLAGS = -Wall -Wextra
WARN_CPPFLAGS =
WARN_LDFLAGS =
WARN_LDLIBS =

ALL_CFLAGS = $(LIBARCHIVE_CFLAGS) $(OPENSSL_CFLAGS) $(WARN_CFLAGS) $(CFLAGS) $(MYCFLAGS)
ALL_CPPFLAGS = $(LIBARCHIVE_CPPFLAGS) $(OPENSSL_CPPFLAGS) $(WARN_CPPFLAGS) $(CPPFLAGS) $(MYCPPFLAGS)
ALL_LDFLAGS = $(LIBARCHIVE_LDFLAGS) $(OPENSSL_LDFLAGS) $(WARN_LDFLAGS) $(LDFLAGS) $(MYLDFLAGS)
ALL_LDLIBS = $(MYLDLIBS) $(LDLIBS) $(LIBARCHIVE_LDLIBS) $(OPENSSL_LDLIBS) $(WARN_LDLIBS)

tarsum: tarsum.c
	$(CC) -o $@ $< $(ALL_CFLAGS) $(ALL_CPPFLAGS) $(ALL_LDFLAGS) $(ALL_LDLIBS)

clean:
	$(RM) -f tarsum
	$(RM) -fr tarsum.dSYM
